### ISSUE TITLE
Replace calls to Double.doubleToRawLongBits and Float.floatToRawIntBits with non-raw versions.

### ISSUE THREAD

**Issue by lambdaknight** [trueaccord/protobuf-scala-runtime#6]
You should be able to replace the above functions with `Double.doubleToLongBits` and `Float.floatToIntBits` safely. Please do this. Otherwise, scalaPB on ScalaJS is worthless for any protobuf definition that contains floats or doubles.

**Comment by thesamet** [comment]
Fixed in v0.1.12
